/**
 * Словарь фраз: 1024 русских слова латиницей, ровно 10 бит на слово.
 *
 * Сгенерирован из docs/crypto/dictionary-ru-latin-1024.txt — править там,
 * затем пересобрать этот файл (тест WordsTest следит, чтобы они не разошлись).
 * Правила отбора слов — docs/crypto/crypto-spec-product3.md, раздел 4.
 *
 * sha256 исходного списка: 68db27c5e67cc388812226c33b7dfd89849554a9fa7b03001a69b6def5fb675e
 */
export const WORDS = Object.freeze([
    'korova', 'sobaka', 'koshka', 'loshad', 'medved', 'volki', 'lisitsa', 'zayats', 'barsuk', 'bobyor', 'krolik', 'khomyak',
    'belka', 'olen', 'losos', 'karas', 'okun', 'delfin', 'kitenok', 'morzh', 'tyulen', 'pingvin', 'sokol', 'orlan',
    'vorona', 'soroka', 'golub', 'sinitsa', 'snegir', 'dyatel', 'zhuravl', 'tsaplya', 'utka', 'gusenok', 'petukh', 'indyuk',
    'pavlin', 'filin', 'sova', 'zhuk', 'pchela', 'shmel', 'muravey', 'kuznets', 'ulitka', 'begemot', 'zhiraf', 'zebra',
    'gazel', 'lama', 'alpaka', 'buyvol', 'bizon', 'kaban', 'baran', 'ovtsa', 'kozyol', 'poni', 'osel', 'lvitsa',
    'leopard', 'gepard', 'pantera', 'panda', 'koala', 'kenguru', 'enot', 'vydra', 'kunitsa', 'surok', 'suslik', 'tushkan',
    'ezhonok', 'krot', 'bereza', 'dubok', 'sosna', 'listva', 'klyon', 'lipa', 'ryabina', 'osina', 'olkha', 'topol',
    'verba', 'ivushka', 'yasen', 'kashtan', 'platan', 'akatsia', 'grusha', 'sliva', 'vishnya', 'persik', 'abrikos', 'ayva',
    'inzhir', 'granat', 'khurma', 'apelsin', 'limon', 'ananas', 'kokos', 'finik', 'izyum', 'oreshek', 'funduk', 'mindal',
    'rozh', 'yachmen', 'oves', 'grechka', 'fasol', 'gorokh', 'svyokla', 'repka', 'redis', 'kapusta', 'ogurets', 'pomidor',
    'perets', 'tykva', 'dynya', 'arbuz', 'malina', 'klyukva', 'buzina', 'gribok', 'opyonok', 'gruzdok', 'ryzhik', 'tryufel',
    'mokh', 'kamysh', 'osoka', 'klever', 'landysh', 'fialka', 'pion', 'lilia', 'georgin', 'astra', 'lavanda', 'myata',
    'melissa', 'shalfey', 'bazilik', 'ukrop', 'kinza', 'tarkhun', 'khren', 'chesnok', 'lukovka', 'imbir', 'kurkuma', 'koritsa',
    'vanil', 'shafran', 'tmin', 'khleb', 'baton', 'blin', 'pirog', 'sushka', 'pryanik', 'biskvit', 'zefir', 'pastila',
    'khalva', 'nuga', 'varenye', 'povidlo', 'dzhem', 'sirop', 'sakhar', 'solonka', 'uksus', 'maslo', 'smetana', 'tvorog',
    'brynza', 'moloko', 'yaytso', 'omlet', 'borshch', 'shchi', 'ukha', 'bulyon', 'lapsha', 'pelmeni', 'kotleta', 'tefteli',
    'zharkoe', 'kolbasa', 'sosiska', 'bekon', 'salo', 'okorok', 'farsh', 'gulyash', 'plov', 'rizotto', 'grenka', 'salatik',
    'zakuska', 'desert', 'kompot', 'kisel', 'mors', 'kvasok', 'chaynik', 'zavarka', 'kruzhka', 'stakan', 'bokal', 'ryumka',
    'tarelka', 'mishka', 'lozhka', 'vilka', 'nozhik', 'lopatka', 'venchik', 'tyorka', 'sito', 'forma', 'doska', 'skalka',
    'stupka', 'pestik', 'bank', 'kryshka', 'probka', 'butylka', 'flakon', 'vedro', 'korzina', 'meshok', 'sumka', 'ryukzak',
    'papka', 'konvert', 'larets', 'komod', 'shkaf', 'polka', 'tumba', 'stol', 'kreslo', 'divan', 'tabure', 'lavka',
    'krovat', 'matras', 'odeyalo', 'pledik', 'kover', 'shtora', 'karniz', 'lyustra', 'torsher', 'nochnik', 'fonarik', 'svecha',
    'kamin', 'pechka', 'truba', 'kotel', 'pylesos', 'shvabra', 'tryapka', 'gubka', 'metla', 'sovok', 'musorka', 'mylo',
    'shampun', 'balzam', 'krem', 'losyon', 'zerkalo', 'domik', 'izba', 'khata', 'terem', 'dvorets', 'zamok', 'bashnya',
    'krepost', 'stena', 'zabor', 'kalitka', 'dver', 'okoshko', 'steklo', 'krylco', 'perila', 'podval', 'pogreb', 'sarai',
    'ambar', 'besedka', 'kacheli', 'gorka', 'gamak', 'zont', 'lezhak', 'mangal', 'kostyor', 'drova', 'polenya', 'pila',
    'gvozd', 'shurup', 'vint', 'gayka', 'bolt', 'shayba', 'rubanok', 'sverlo', 'drel', 'lobzik', 'rulet', 'lineyka',
    'ugolnik', 'uroven', 'tsirkul', 'ruchka', 'marker', 'kist', 'kraska', 'grunt', 'shpatel', 'valik', 'klei', 'skotch',
    'kanat', 'tros', 'tsep', 'provod', 'kabel', 'rozetka', 'motor', 'nasos', 'turbina', 'porshen', 'klapan', 'remen',
    'rychag', 'pedal', 'shina', 'disk', 'tormoz', 'kuzov', 'kapot', 'bamper', 'fara', 'sidenye', 'avtobus', 'tramvay',
    'metro', 'poezd', 'vagon', 'vokzal', 'perron', 'bilet', 'garazh', 'doroga', 'shosse', 'trassa', 'bulvar', 'skver',
    'park', 'most', 'tunnel', 'znak', 'trotuar', 'bordyur', 'urna', 'fontan', 'statuya', 'obelisk', 'arka', 'kolonna',
    'kupol', 'shpil', 'flyuger', 'kirpich', 'tsement', 'pesok', 'glina', 'izvest', 'gips', 'oboi', 'laminat', 'paneli',
    'profil', 'svaya', 'setka', 'rulon', 'dvutavr', 'polosa', 'prutok', 'folga', 'lenta', 'shnur', 'tesma', 'tkan',
    'sitets', 'satin', 'flanel', 'sherst', 'dzhins', 'velvet', 'barkhat', 'shelk', 'atlas', 'kapron', 'neylon', 'khlopok',
    'kozha', 'zamsha', 'vata', 'pukh', 'pero', 'volokno', 'klubok', 'spitsy', 'igolka', 'bulavka', 'molniya', 'knopka',
    'petlya', 'poyas', 'sharf', 'kosynka', 'shapka', 'shlyapa', 'panama', 'noski', 'chulki', 'bluzka', 'sviter', 'zhilet',
    'pidzhak', 'kurtka', 'palto', 'plashch', 'shuba', 'bryuki', 'shorty', 'pizhama', 'trusy', 'tufli', 'botinki', 'sapogi',
    'valenki', 'kedy', 'shlepki', 'kaloshi', 'kabluk', 'stelka', 'solntse', 'luna', 'zvezda', 'kometa', 'planeta', 'orbita',
    'rassvet', 'zakat', 'sumerki', 'polden', 'polnoch', 'utro', 'vecher', 'nedelya', 'mesyats', 'godik', 'vesna', 'leto',
    'zima', 'ottepel', 'moroz', 'inei', 'sosulka', 'sugrob', 'luzha', 'grom', 'liven', 'raduga', 'tuman', 'dymka',
    'oblako', 'tucha', 'veter', 'priboy', 'volna', 'otliv', 'priliv', 'vodopad', 'protoka', 'ozero', 'prud', 'rodnik',
    'istok', 'ustye', 'delta', 'zaliv', 'bukhta', 'ostrov', 'riff', 'atoll', 'plyazh', 'dyuna', 'utyos', 'valun',
    'mramor', 'bazalt', 'slantsy', 'kvarts', 'almaz', 'izumrud', 'rubin', 'sapfir', 'topaz', 'ametist', 'yantar', 'koral',
    'zoloto', 'serebro', 'latun', 'chugun', 'zhelezo', 'tsink', 'olovo', 'svinets', 'nikel', 'titan', 'volfram', 'grafit',
    'torf', 'neft', 'benzin', 'kerosin', 'mazut', 'smola', 'vosk', 'parafin', 'kholm', 'sklon', 'kanyon', 'ravnina',
    'prerii', 'savanna', 'oazis', 'tayga', 'tundra', 'roshcha', 'opushka', 'polyana', 'vyrubka', 'gryadka', 'ogorod', 'senokos',
    'zhatva', 'urozhay', 'snop', 'zerno', 'muka', 'otrubi', 'mulcha', 'semya', 'rostok', 'pobeg', 'suchok', 'pyltsa',
    'nektar', 'yagoda', 'shishka', 'golova', 'brov', 'veko', 'glaz', 'zrachok', 'nozdrya', 'yazyk', 'gorlo', 'plecho',
    'lokot', 'ladon', 'palets', 'nogot', 'kulak', 'rebro', 'zhivot', 'koleno', 'stopa', 'pyatka', 'serdtse', 'mozg',
    'nerv', 'myshtsa', 'sustav', 'skelet', 'cherep', 'skripka', 'gitara', 'domra', 'fleyta', 'klarnet', 'goboy', 'fagot',
    'trombon', 'piano', 'royal', 'garmon', 'volynka', 'litavry', 'buben', 'marakas', 'gong', 'nota', 'akkord', 'gamma',
    'oktava', 'tonika', 'ritm', 'takt', 'pauza', 'pripev', 'motiv', 'romans', 'ballada', 'sonata', 'etyud', 'vals',
    'tango', 'gimn', 'khor', 'ansambl', 'orkestr', 'plotnik', 'gonchar', 'tkach', 'portnoy', 'pekar', 'povar', 'melnik',
    'rybak', 'lesnik', 'konyukh', 'doyarka', 'tokar', 'slesar', 'malyar', 'voditel', 'pilot', 'kapitan', 'bocman', 'vrach',
    'aptekar', 'uchitel', 'geolog', 'biolog', 'khimik', 'graver', 'yuvelir', 'akter', 'tantsor', 'akrobat', 'kloun', 'zelyony',
    'zhyolty', 'rozovy', 'sery', 'chyorny', 'bely', 'bezhevy', 'alyi', 'bagrovy', 'lilovy', 'lazurny', 'khaki', 'medny',
    'stalnoy', 'sazhevy', 'snezhny', 'tyoply', 'suhoy', 'vlazhny', 'myagky', 'tvyordy', 'gladky', 'lyogky', 'gustoy', 'zhidky',
    'rykhly', 'prochny', 'khrupky', 'gibky', 'zhestky', 'uprugy', 'lipky', 'skolzky', 'puhisty', 'mutny', 'yarky', 'tuskly',
    'matovy', 'pyostry', 'reznoy', 'litoy', 'kovany', 'plavit', 'tochit', 'strogat', 'paiat', 'varit', 'klepat', 'shit',
    'vyazat', 'plesti', 'meryat', 'schitat', 'delit', 'risovat', 'polivat', 'kosit', 'veyat', 'solit', 'koptit', 'vyalit',
    'mesit', 'podavat', 'azart', 'bagor', 'bochka', 'brevno', 'bryzgi', 'buket', 'burya', 'charka', 'chashka', 'cheln',
    'chizh', 'chudo', 'dacha', 'dekada', 'delo', 'dengi', 'derzhat', 'dikiy', 'dnevnik', 'dobro', 'dogovor', 'dolina',
    'dozhd', 'drug', 'duma', 'dusha', 'dyra', 'echo', 'epokha', 'etazh', 'fakel', 'fantik', 'farfor', 'fasad',
    'fevral', 'figura', 'flag', 'fokus', 'fond', 'forel', 'fraza', 'frukt', 'gavan', 'gazon', 'gerb', 'geroy',
    'gnezdo', 'gody', 'gordost', 'grabli', 'grad', 'gudok', 'igla', 'ikra', 'imya', 'indeks', 'istina', 'ivolga',
    'izgib', 'izlom', 'kadr', 'kadka', 'kalach', 'kamera', 'karta', 'katok', 'kegli', 'khobot', 'khokkey', 'khutor',
    'kino', 'kislota', 'klad', 'kletka', 'klimat', 'klumba', 'kniga', 'kobyla', 'kolpak', 'komnata', 'konek', 'konus',
    'kopye', 'korm', 'kosa', 'kray', 'kredo', 'krik', 'krupa', 'kupets', 'kurort', 'kuvshin', 'kvota', 'lasty',
    'lazer', 'lebed', 'legenda', 'leshiy', 'lezvie', 'lider', 'litr', 'lodka', 'logika', 'lotok', 'lozung', 'luchik',
    'lyudi', 'lyuk', 'magnit', 'maket', 'mantiya', 'mashina', 'maska', 'mayak', 'mebel', 'mechta', 'melok', 'menu',
    'merka', 'mesto', 'metod', 'mikser', 'milya', 'minus', 'mira', 'mnenie', 'moda', 'model', 'moneta', 'moped',
    'muzey', 'nadel', 'nagrada', 'nalog', 'namek', 'napitok', 'narod', 'nauka', 'nerpa', 'nitka', 'nomer', 'novost',
    'nyanya', 'obed', 'oblik', 'obraz', 'obruch', 'obychay', 'ocherk', 'odezhda', 'ofis', 'ogon', 'okhota', 'okno',
    'okrug', 'opeka', 'opora', 'opyt', 'orden', 'oreol', 'orekh', 'osnova', 'otchet', 'otdykh', 'otets', 'otvet',
    'palata', 'palma', 'paren', 'partiya', 'pavodok', 'pena', 'pensiya', 'pesnya', 'pichuga', 'piket', 'pismo', 'plakat',
    'plamya', 'pochta', 'poema', 'poet', 'pokoy', 'posev', 'posylka', 'pravda', 'predel', 'premiya', 'prizma', 'progon',
    'prostor', 'punkt', 'rabota', 'radost', 'ramka', 'rang', 'rasa', 'raschet', 'razdel', 'rebus', 'rekord', 'respekt',
    'retsept', 'rezerv', 'rezhim', 'rezina', 'rifma', 'rodina', 'roskosh', 'rubl', 'ruda', 'salyut', 'samovar', 'sani',
    'sektor', 'seriya', 'shag', 'shans', 'shema', 'shkola', 'shkura', 'shtab', 'shum', 'simvol', 'skorost', 'sled',
    'sloy', 'sluchay', 'smysl', 'sobor', 'soldat', 'sosed', 'sotnya', 'soyuz', 'spisok', 'sport', 'sreda', 'stado',
    'start', 'stikh', 'storona', 'strana', 'strela', 'stuk', 'sudno', 'sudba', 'svet', 'svoboda', 'svyaz', 'tabak',
    'teatr', 'tekst', 'telega', 'tempo', 'tenor', 'tent', 'tikhiy', 'titul', 'tolpa', 'tonna', 'topka', 'traktor',
    'trek', 'trend', 'trepet', 'tretiy', 'trofey', 'troika', 'tsar', 'tsentr', 'tsifra', 'udar', 'ugroza', 'ukaz',
    'umenie', 'uporen', 'usadba', 'uslovie', 'uspekh', 'utes', 'utyug', 'uzel', 'uzor', 'vakhta', 'valyuta', 'vekha',
    'venets', 'verkh', 'vershok', 'vesy',
]);

export const WORDS_SHA256 = '68db27c5e67cc388812226c33b7dfd89849554a9fa7b03001a69b6def5fb675e';
